---
- name: deploy httpd playbook
  hosts: all
  become: yes

  tasks:
    - name: install httpd service
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: enable and start httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: enable http service on firewalld
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
